name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'


      - name: slack-upload
        uses: MeilCli/slack-upload-file@v3
        with:
            slack_token: ${{ secrets.SLACK_TOKEN }}
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            file_path: 'trivy-results.sarif'
            initial_comment: 'post by slack-upload-file'
        
      - name: build and push
        run: |
         doker build -t app .
         doker login -u:${{secrets.DOCKERHUB_USERNAME}} -p:${{secrets.DOCKERHUB_TOKEN}}
         doker tag app freddychen5/testnew

         
                    
        
        
            

          

