name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          output: 'trivy-results.txt'
          
      - name: Upload Scan Results
        if: steps.Build.output.trivy-results.txt == 'true'
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy-results.txt'
          initial_comment: 'post by slack-upload-file'

      - name: build and push container
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            docker.io/freddychen5/testnew:${{ github.sha }}

      - name: Sign Docker Image
        run: cosign sign -key /Users/freddy/Downloads/fortunes01/cosign.key  docker.io/freddychen5/testnew:${{ github.sha }}
      - name: Push Signed Image
        run: docker push docker.io/freddychen5/testnew:${{ github.sha }}

      - name: Push Signed Image
        run: docker push docker.io/freddychen5/testnew:${{ github.sha }}


    


         
                    
        
        
            

          

